### ISSUE TITLE
error state seems to be inconsistent to other states

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#343] opened 2021-11-08 20:36 UTC
**Is your feature request related to a problem? Please describe.**

All other states accept JQ input for their fields. The error state can only accept a string for the *error* field. I wanted to catch an error, handle it and then still raise it after. The use-case would be to do jq(.error.code) in the error field. 

The message has the same "issue". If it would be JQ instead of the args field it would be easier to use because Direktiv has a basically a sprintf with jq.

Now: 

```
- id: error-out-of-date
  type: error
  error: validation.outOfDate
  message: "food item %s is out of date"
  args:
  - jq(.item.name)
```
New
```
- id: error-out-of-date
  type: error
  error: jq(.whatever) OR my.new.error
  message: 'This is an error jq(.myvalue)'
```

**Comment by alankm** [comment] 2021-11-08 21:26
I'm not sure if this works as intended the way it's described. Can you provide a more complete example for how it would be used?

**Comment by jensg-st** [comment] 2021-11-08 23:00
The example is in the "New" part. The type is string only. And the message is strange because everywhere else, e.g. logs, you can use jq. Why not in errors? Why do we have a custom sprintf?

**Comment by alankm** [comment] 2021-11-08 23:50
On the `message` field, it's true that this pattern was designed before our modern `jq` logic. The current method still arguably is more powerful because `printf` gives you a lot of control over the output format. I agree that the power probably isn't worth the inconsistency though. I'm in favour of changing it to a single `jq` field.

On the `error` field, I'm not so sure about this. I can see the it being used in some cases. Probably rare ones. But I like right now that you can easily tell exactly what errors a workflow can throw just by looking at the YAML.

**Comment by alankm** [comment] 2022-01-14 02:11
We've merged something that partially addresses this issue. It makes it possible to generate the message via embedded jq. 

We haven't made the code itself variable at this stage. I believe we discussed this and had good reasons both for and against. Are we happy to close this issue? Or do we want to make the codes variable as well?

**Closed** 2022-01-17 22:31 UTC
Labels: enhancement
